-- SQL File for Digital Sovereignty Questions
-- Compatible with MySQL/MariaDB. Use JSON_TEXT column type for flexibility with PDO.
--
-- Table: questions_souverainete
--
-- Colonnes :
--   id: Identifiant unique.
--   type: Type de question ('choice', 'match', 'gap').
--   question_text: Le texte principal de la question.
--   data_json: Contient les options, paires, ou mots à compléter (format JSON).
--   description: L'explication pédagogique de la réponse.
--   analogy: L'analogie concrète pour la vulgarisation.

DROP TABLE IF EXISTS `questions_souverainete`;

CREATE TABLE `questions_souverainete` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(10) NOT NULL,
  `question_text` TEXT NOT NULL,
  `data_json` TEXT NOT NULL,
  `description` TEXT NOT NULL,
  `analogy` TEXT DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `leaderboard` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `player_name` VARCHAR(50) NOT NULL,
  `score` INT(11) NOT NULL,
  `date_achieved` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

--
-- Insertion des données (35 questions)
--

INSERT INTO `questions_souverainete` (`type`, `question_text`, `data_json`, `description`, `analogy`) VALUES
-- --- TYPE: QCM (CHOICE) ---
('choice', 'L''école stocke mes photos sur un ''Cloud'' américain. Qui a le droit de les regarder selon la loi américaine ?', '{"options": ["Seulement moi", "Le directeur de l''école", "La justice américaine (CLOUD Act)", "Personne"], "correct": 2}', 'Les lois américaines permettent à leurs services de renseignement d''accéder aux données, même si elles sont stockées en France.', 'C''est comme si vous louiez un coffre-fort à Paris, mais que la police de New York avait le double des clés.'),
('choice', 'Pourquoi dit-on que Google ou Facebook ne sont pas ''gratuits'' ?', '{"options": ["Ils demandent des dons", "Ils vendent mes données personnelles (pub)", "L''État paie pour nous", "C''est une erreur"], "correct": 1}', 'Leur modèle économique est la publicité ciblée. Ils analysent tout ce que vous faites pour vendre ce profil à des marques.', 'Si le sandwich est gratuit, c''est que vous êtes le jambon !'),
('choice', 'Je veux envoyer un gros fichier vidéo à mes élèves sans passer par Google/WeTransfer.', '{"options": ["Je l''imprime", "J''utilise un ''Drive'' libre (Nextcloud)", "Je le coupe en morceaux", "C''est impossible"], "correct": 1}', 'Des outils comme Nextcloud permettent à l''école de gérer ses propres fichiers sans qu''ils soient analysés par des robots publicitaires.', 'C''est la différence entre mettre vos documents dans votre armoire privée (Nextcloud) ou les poser sur un banc public (Google).'),
('choice', 'L''école achète uniquement des tablettes d''une marque très fermée. Quel est le risque ?', '{"options": ["Elles sont trop jolies", "Le verrouillage technologique (dépendance)", "Elles vont exploser", "Aucun risque"], "correct": 1}', 'Si on s''habitue à un seul système, il devient très coûteux et difficile d''en changer plus tard (logiciels incompatibles, rachat de matériel...).', 'C''est comme acheter une machine à café qui n''accepte qu''une seule marque de capsules très chères.'),
('choice', 'Quel est le principal avantage de LibreOffice par rapport à Microsoft Office dans le cadre scolaire ?', '{"options": ["C''est plus rapide", "C''est un Logiciel Libre dont le code est vérifiable", "Il a plus de fonctionnalités", "Il est préinstallé partout"], "correct": 1}', 'Le code est public, ce qui garantit qu''il n''y a pas de fonction cachée d''espionnage ou de télémétrie.', 'C''est comme avoir un plan détaillé du moteur de votre voiture.'),
('choice', 'Un format de fichier ''ouvert'' (comme .odt) garantit :', '{"options": ["Que le fichier est petit", "La pérennité de l''information et l''interopérabilité", "Qu''il est toujours modifiable", "Rien du tout"], "correct": 1}', 'Si l''entreprise qui a créé le logiciel fait faillite, un format ouvert pourra toujours être lu par d''autres logiciels.', 'Votre vieille cassette VHS peut encore être lue sur n''importe quel magnétoscope, car le format est connu de tous.'),
('choice', 'Pourquoi l''utilisation d''un navigateur comme Firefox est préférable à Chrome ?', '{"options": ["Il est plus joli", "Il n''est pas basé sur la technologie de Google", "Il est plus rapide", "Il est mieux optimisé pour le mobile"], "correct": 1}', 'Firefox utilise son propre moteur (Gecko), évitant de laisser Google décider seul des standards du Web mondial.', 'Avoir plusieurs marques de voitures différentes est mieux que si tout le monde utilisait le moteur d''une seule marque.'),
('choice', 'Quel est le but principal de la loi européenne RGPD ?', '{"options": ["Taxer les GAFAM", "Protéger les données personnelles des citoyens", "Réguler le commerce électronique", "Standardiser le Wi-Fi"], "correct": 1}', 'Le Règlement Général sur la Protection des Données vous donne le contrôle de vos informations personnelles.', 'C''est votre droit de savoir qui sonne à la porte et pourquoi.'),
('choice', 'Si l''école met en place un ENT souverain, cela signifie qu''elle...', '{"options": ["Le loue à Google", "L''héberge sur des serveurs sous contrôle européen", "N''a plus besoin d''internet", "N''utilise que des Macs"], "correct": 1}', 'La souveraineté numérique passe par l''hébergement sur le territoire où s''applique le droit européen.', 'C''est comme avoir votre propre jardin plutôt que de faire pousser vos fruits chez le voisin.'),
('choice', 'Quel risque principal pose le concept de ''Télémétrie'' pour l''école ?', '{"options": ["Le logiciel devient trop rapide", "Le logiciel envoie des données d''utilisation détaillées à l''éditeur", "Le logiciel devient lent", "La connexion Wi-Fi est coupée"], "correct": 1}', 'La télémétrie peut transmettre des informations sur les habitudes d''utilisation et le comportement des élèves sans leur consentement éclairé.', 'C''est un mouchard qui rapporte tout ce que vous faites à la maison, même ce qui n''a rien à voir avec le logiciel.'),

-- --- TYPE: ASSOCIATION (MATCH) ---
('match', 'Reliez chaque géant du Web (GAFAM) à son alternative éthique et libre !', '[{"left": "YouTube 📹", "right": "PeerTube 🐙"}, {"left": "Google Drive 📁", "right": "Nextcloud ☁️"}, {"left": "Zoom 🎥", "right": "BigBlueButton 🎓"}, {"left": "WhatsApp 💬", "right": "Signal 🔒"}]', 'Il existe une alternative libre pour presque tous les outils connus ! Ces alternatives respectent votre vie privée.', 'C''est comme choisir entre un supermarché géant qui vous surveille (GAFAM) et une coopérative locale de confiance (Libre).'),
('match', 'Associez le problème à sa conséquence.', '[{"left": "Données aux USA 🇺🇸", "right": "Espionnage potentiel 🕵️"}, {"left": "Logiciel fermé 🔒", "right": "Impossible à vérifier ❌"}, {"left": "Logiciel Libre 🐧", "right": "Transparence totale ✅"}, {"left": "Obsolescence matérielle ♻️", "right": "Gaspillage d''argent et pollution"}]', 'Comprendre ces liens permet de mieux choisir ses outils numériques.', 'Un logiciel fermé, c''est comme un plat au restaurant dont le chef refuse de donner la liste des ingrédients (allergies ?).'),
('match', 'Associez le concept à sa définition.', '[{"left": "RGPD 🇪🇺", "right": "Protection des données personnelles"}, {"left": "Interoperabilité 🔄", "right": "Systèmes capables de communiquer"}, {"left": "Métadonnées 🏷️", "right": "Infos sur l''info (Qui, Quand, Où)"}, {"left": "Verrouillage 🔗", "right": "Difficulté de changer de fournisseur"}]', 'Ce sont les piliers de la discussion sur l''éthique numérique.', 'Les métadonnées, c''est le facteur qui compte pour la poste (nom, adresse), pas le contenu de la lettre elle-même.'),
('match', 'Reliez l''outil propriétaire à son équivalent bureautique libre.', '[{"left": "Microsoft Word", "right": "Writer (LibreOffice)"}, {"left": "Google Sheets", "right": "Calc (LibreOffice)"}, {"left": "Microsoft Teams", "right": "Jitsi Meet"}, {"left": "Dropbox", "right": "Nextcloud Files"}]', 'Chaque outil GAFAM a son jumeau éthique et souvent plus puissant !', 'La diversité des outils est synonyme de résilience.'),

-- --- TYPE: TEXTE A TROUS (GAP) ---
('gap', 'Complétez cette phrase célèbre.', '{"sentence": "Si c''est gratuit, c''est que vous êtes le [1].", "answers": ["produit"], "fake": ["client", "gagnant", "patron"]}', 'Cette phrase résume l''économie de l''attention. Votre temps de cerveau et vos infos sont la monnaie d''échange.', 'On ne paie pas avec de l''argent, mais avec sa vie privée.'),
('gap', 'Complétez pour comprendre l''Open Source.', '{"sentence": "Un logiciel libre est comme une recette de cuisine : tout le monde a le droit de la [1] et de l''améliorer.", "answers": ["partager"], "fake": ["vendre", "cacher", "détruire"]}', 'La liberté de partager et modifier est au cœur du logiciel libre (comme Wikipédia).', 'Si vous améliorez la recette du gâteau au chocolat, tout le monde en profite !'),
('gap', 'La souveraineté numérique.', '{"sentence": "Pour être souveraine, l''école doit garder le [1] sur les données des élèves.", "answers": ["contrôle"], "fake": ["silence", "monopole", "suspe"]}', 'Garder le contrôle signifie savoir exactement où sont les données et qui y touche.', 'C''est être propriétaire de sa maison plutôt que locataire chez Google.'),
('gap', 'L''une des quatre libertés fondamentales du logiciel libre est de pouvoir [1] le programme.', '{"sentence": "L''une des quatre libertés fondamentales du logiciel libre est de pouvoir [1] le programme.", "answers": ["modifier"], "fake": ["verrouiller", "acheter", "revendre"]}', 'Pouvoir modifier le logiciel permet de l''adapter aux besoins spécifiques de l''enseignement et de corriger les failles de sécurité.', 'Si la porte est mal faite, vous avez le droit de la réparer vous-même.'),
('gap', 'Le [1] est une loi européenne qui définit le cadre de la protection des données personnelles.', '{"sentence": "Le [1] est une loi européenne qui définit le cadre de la protection des données personnelles.", "answers": ["RGPD"], "fake": ["TVA", "GAAP", "TICE"]}', 'Le RGPD est notre bouclier juridique contre l''exploitation abusive des données.', 'C''est le code de la route de l''information personnelle.'),

-- Remplissage pour atteindre 35
('choice', 'Quel est le risque de sécurité quand on utilise un logiciel dont le code source est fermé ?', '{"options": ["Il coûte cher", "Il y a plus de bugs", "Personne ne peut vérifier s''il y a des failles ou des portes dérobées", "Il est trop simple"], "correct": 2}', 'Le code fermé est un risque car seule l''entreprise peut le voir. Dans un code ouvert (libre), des milliers d''experts peuvent vérifier sa sécurité.', 'C''est comme si votre serrure était brevetée : vous ne pouvez pas vérifier si elle a des défauts.'),
('choice', 'L''installation de Linux sur d''anciens ordinateurs scolaires permet de lutter contre :', '{"options": ["Le bruit", "L''obsolescence programmée", "Le piratage", "Les virus"], "correct": 1}', 'Linux est léger et peu gourmand. Il permet de réutiliser des machines de 10 ans, luttant contre le gaspillage électronique.', 'C''est la deuxième vie de vos vieux appareils.'),
('choice', 'Pour l''école, que signifie l''indépendance vis-à-vis des financements publicitaires ?', '{"options": ["Moins d''argent", "Une meilleure qualité d''enseignement", "L''absence de ciblage et de pistage des élèves", "Plus de publicité"], "correct": 2}', 'Si l''outil ne fait pas de publicité, il n''a pas besoin de pister les élèves, garantissant un environnement d''apprentissage neutre.', 'Un cours de maths sans coupure publicitaire sur les jeux vidéo.'),
('choice', 'CryptPad est un outil de collaboration qui utilise le chiffrement :', '{"options": ["Sur le serveur uniquement", "De bout en bout (client-client)", "Jamais", "Seulement pour les mots de passe"], "correct": 1}', 'Le chiffrement de bout en bout garantit que même le gérant du serveur ne peut pas lire le contenu de vos documents.', 'Seuls vous et votre équipe avez la clé du document.'),
('choice', 'Quelle association française est très active dans la promotion des alternatives libres à l''école ?', '{"options": ["Ligue des Champions", "Framasoft", "Google Foundation", "Microsoft France"], "correct": 1}', 'Framasoft est à l''origine de la campagne ''Dégooglisons Internet'' et propose de nombreux outils libres.', 'Leur mission : un Internet plus éthique.'),
('choice', 'L''interopérabilité des systèmes informatiques est importante car elle permet :', '{"options": ["D''avoir un seul ordinateur", "Aux différents logiciels de communiquer entre eux", "De tout mettre sur Google", "De payer moins cher"], "correct": 1}', 'Si les systèmes sont interopérables, vous n''êtes pas bloqué chez un seul fournisseur.', 'Vous pouvez envoyer une lettre d''une marque de papier à une autre sans problème.'),
('choice', 'Pourquoi éviter d''utiliser des plateformes américaines pour héberger les notes des élèves ?', '{"options": ["Elles sont trop lentes", "Les notes sont trop sensibles pour être sous juridiction étrangère", "Elles sont trop chères", "Les élèves n''aiment pas"], "correct": 1}', 'Les notes sont des données sensibles (caractère éducatif/social) qui doivent rester sous la protection du RGPD.', 'C''est la loi qui l''exige.'),
('choice', 'Un serveur fédéré, comme celui de PeerTube, permet de :', '{"options": ["Regarder des vidéos en 3D", "Créer un réseau de petites plateformes vidéo connectées entre elles", "Héberger des jeux vidéo", "Pirater des films"], "correct": 1}', 'Chaque école pourrait avoir son propre serveur PeerTube, tout en partageant ses vidéos avec les autres écoles (le Fediverse).', 'Comme une chaîne d''hôtels indépendants qui partagent leur réservation en ligne.'),
('choice', 'Quel moteur de recherche donne la priorité à la vie privée ?', '{"options": ["Google", "Bing", "Qwant / DuckDuckGo", "Yahoo"], "correct": 2}', 'Ces moteurs ne tracent pas vos recherches et ne créent pas de profil publicitaire de vous.', 'Ils effacent leurs traces après votre passage.'),
('choice', 'L''alternative à Android pour les téléphones, qui est dégooglisée, est souvent basée sur :', '{"options": ["Windows", "Une version d''Android sans services Google (ex: /e/OS)", "iOS", "BlackBerry OS"], "correct": 1}', 'Ces systèmes suppriment les mouchards Google tout en gardant la compatibilité des applications Android.', 'Votre téléphone, mais sans les caméras cachées.'),

-- QCM de remplissage
('choice', 'Quelle suite bureautique libre est la plus utilisée par le secteur public en Europe ?', '{"options": ["G Suite", "OnlyOffice / LibreOffice", "Microsoft 365", "Apple iWork"], "correct": 1}', 'De nombreuses administrations migrent vers OnlyOffice (pour la collaboration) ou LibreOffice (pour l''installation locale).', 'C''est la solution choisie par l''armée et la police dans certains pays pour des raisons de sécurité.'),
('choice', 'Quelle est la principale critique faite au logiciel propriétaire dans l''enseignement ?', '{"options": ["Il coûte cher", "Il peut créer une dépendance et un monopole", "Il est trop simple à utiliser", "Il est trop lent"], "correct": 1}', 'Le monopole d''une seule entreprise limite la liberté de choix et l''innovation.', 'Un seul joueur sur le marché, c''est rarement bon pour le client.'),
('choice', 'Un VPN permet principalement de :', '{"options": ["Télécharger des films", "Changer de pays virtuellement", "Chiffrer et sécuriser sa connexion internet", "Bloquer les publicités"], "correct": 2}', 'Dans l''éducation, un VPN protège les données lors de l''utilisation de Wi-Fi publics ou non sécurisés.', 'C''est un tunnel secret chiffré.'),
('choice', 'Qu''est-ce que l''effet de réseau dans le contexte des GAFAM ?', '{"options": ["Un bon signal Wi-Fi", "Plus un service a d''utilisateurs, plus il devient indispensable", "Un réseau social qui s''éteint", "Une panne d''internet"], "correct": 1}', 'Plus il y a d''amis sur Facebook, plus il est difficile de partir, même si l''outil ne vous plaît pas.', 'Plus il y a de téléphones qui utilisent un même chargeur, plus ce chargeur devient la norme.'),
('choice', 'Qu''est-ce qu''un LMS libre ?', '{"options": ["Un système de gestion de l''apprentissage open source (ex: Moodle)", "Un logiciel de messagerie", "Une application de notes", "Un réseau social d''entreprise"], "correct": 0}', 'Moodle permet de créer des cours en ligne, de gérer les devoirs et les interactions avec les élèves, sans frais de licence.', 'La classe virtuelle, sans Big Tech.'),
('choice', 'Quelle est la définition du terme ''métadonnée'' ?', '{"options": ["La donnée la plus importante", "Les informations qui décrivent une donnée (ex: l''heure d''un appel)", "Une donnée chiffrée", "Une donnée obsolète"], "correct": 1}', 'Les métadonnées peuvent révéler plus sur vous que le contenu lui-même (ex: parler tous les jours à l''hôpital à 14h).', 'Ce n''est pas le contenu de la lettre, mais l''étiquette de l''enveloppe.'),
('choice', 'Quel est le risque éthique lié à l''utilisation de l''IA des GAFAM pour noter les copies ?', '{"options": ["L''IA est trop lente", "Elle peut perpétuer des biais (racisme, sexisme) cachés dans les données d''entraînement", "Elle est trop chère", "Elle ne sait pas lire"], "correct": 1}', 'Les algorithmes apprennent de données qui peuvent contenir des préjugés sociaux. L''opacité des systèmes propriétaires rend ce risque invisible.', 'Si l''IA apprend des erreurs du passé, elle risque de les reproduire.'),
('choice', 'L''association Framasoft est célèbre pour sa mission de :', '{"options": ["Vente de logiciels", "Dégoogliser Internet", "Promotion d''Apple", "Création de jeux vidéo"], "correct": 1}', 'Elle propose et met en avant une grande quantité d''outils libres pour remplacer les services GAFAM.', 'Leur catalogue est une mine d''or pour les écoles.'),
('choice', 'Pourquoi le logiciel libre est souvent plus sûr que le logiciel propriétaire ?', '{"options": ["Parce qu''il est plus récent", "Parce que des milliers d''yeux peuvent revoir et corriger le code source", "Il est trop compliqué pour les hackers", "Il est gratuit"], "correct": 1}', 'C''est le principe du ''plus il y a de monde qui regarde, moins il y a de failles non découvertes''.', 'La sécurité par la transparence, pas par le secret.'),
('choice', 'Dans le cas d''un ENT, la migration vers un service souverain doit toujours être motivée par :', '{"options": ["La mode", "Le coût de la licence (qui est plus cher)", "La conformité légale et la protection des données élèves", "La vitesse de connexion"], "correct": 2}', 'La priorité absolue est la conformité au RGPD et la protection des données sensibles des mineurs.', 'La loi passe avant le confort.'),
('choice', 'Quel est le risque principal des publicités ciblées sur les plateformes éducatives ?', '{"options": ["Elles sont jolies", "Elles perturbent la concentration et créent des biais de consommation", "Elles donnent de bonnes idées", "Elles n''existent pas"], "correct": 1}', 'L''école doit être un lieu neutre, sans influence publicitaire.', 'L''apprentissage avant la consommation.'),
('choice', 'Un hébergeur français (certifié HDS ou SecNumCloud) est préférable car :', '{"options": ["Il parle français", "Il est sous juridiction européenne (RGPD)", "Il est plus rapide", "Il est moins cher"], "correct": 1}', 'La certification garantit que les données ne peuvent pas être saisies sans mandat européen.', 'Le gendarme est européen, pas américain.'),
('choice', 'Quel outil libre permet de chiffrer les communications instantanées (comme WhatsApp) ?', '{"options": ["Telegram", "Signal", "Skype", "iMessage"], "correct": 1}', 'Signal (ou Olvid) utilise le chiffrement de bout en bout et ne stocke pas les métadonnées.', 'La discussion n''est lue que par les deux participants.'),
('choice', 'Pour l''enseignement, le choix d''un système d''exploitation comme GNU/Linux permet surtout :', '{"options": ["D''économiser l''électricité", "De former les élèves à l''ouverture technologique et la personnalisation", "De n''avoir aucun virus", "De jouer aux jeux vidéo"], "correct": 1}', 'Cela montre aux élèves qu''il existe des alternatives aux systèmes dominants (Windows/Mac) et développe leur esprit critique.', 'C''est une leçon de citoyenneté numérique.');